// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrT9UFFezZTuahiufjt9iG2A79exnMax0',
    appId: '1:304243905922:web:24d3db7678cfafe755eb9b',
    messagingSenderId: '304243905922',
    projectId: 'glovoapotheka',
    authDomain: 'glovoapotheka.firebaseapp.com',
    storageBucket: 'glovoapotheka.firebasestorage.app',
    measurementId: 'G-GLE47EVPH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOz59Xl8okirQDbDh98LJwkIBM2jC9aGY',
    appId: '1:304243905922:android:c641836039eae49f55eb9b',
    messagingSenderId: '304243905922',
    projectId: 'glovoapotheka',
    storageBucket: 'glovoapotheka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxkYb5ylEBLYfkPFYJL-N5V8yvE0qHB3Y',
    appId: '1:304243905922:ios:b3a1a4b1e342559855eb9b',
    messagingSenderId: '304243905922',
    projectId: 'glovoapotheka',
    storageBucket: 'glovoapotheka.firebasestorage.app',
    iosBundleId: 'com.example.glovoapotheka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxkYb5ylEBLYfkPFYJL-N5V8yvE0qHB3Y',
    appId: '1:304243905922:ios:b3a1a4b1e342559855eb9b',
    messagingSenderId: '304243905922',
    projectId: 'glovoapotheka',
    storageBucket: 'glovoapotheka.firebasestorage.app',
    iosBundleId: 'com.example.glovoapotheka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrT9UFFezZTuahiufjt9iG2A79exnMax0',
    appId: '1:304243905922:web:4a37e27031e1d43555eb9b',
    messagingSenderId: '304243905922',
    projectId: 'glovoapotheka',
    authDomain: 'glovoapotheka.firebaseapp.com',
    storageBucket: 'glovoapotheka.firebasestorage.app',
    measurementId: 'G-TJQETB6PHN',
  );
}
