"""Seed some test data

Revision ID: 01a4d753aa07
Revises: 5c5e7b005fde
Create Date: 2025-08-17 16:37:38.557852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01a4d753aa07'
down_revision: Union[str, Sequence[str], None] = '5c5e7b005fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_uid', sa.String(), nullable=False),
    sa.Column('pharmacy_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('qty', sa.String(), nullable=False),
    sa.Column('price_cents_at_booking', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_user_uid'), 'bookings', ['user_uid'], unique=False)
    op.create_table('pharmacies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('lat', sa.String(), nullable=False),
    sa.Column('lng', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacies_name'), 'pharmacies', ['name'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('form', sa.String(), nullable=False),
    sa.Column('strength', sa.String(), nullable=False),
    sa.Column('gtin', sa.String(), nullable=False),
    sa.Column('price_cents', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('pharmacy_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_gtin'), 'products', ['gtin'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_gtin'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_pharmacies_name'), table_name='pharmacies')
    op.drop_table('pharmacies')
    op.drop_index(op.f('ix_bookings_user_uid'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
