"""Added translations table

Revision ID: 0dc2e3b71fd0
Revises: d50e6c863412
Create Date: 2025-09-02 15:18:55.348626

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0dc2e3b71fd0"
down_revision: Union[str, Sequence[str], None] = "d50e6c863412"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DELETE FROM products;")
    op.execute("DELETE FROM pharmacies;")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("brand_name", sa.String(), nullable=False),
        sa.Column("manufacturer", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_brands_brand_name"), "brands", ["brand_name"], unique=False
    )
    op.create_table(
        "translations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("language_code", sa.String(length=5), nullable=False),
        sa.Column("translated_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "packages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("brand_id", sa.String(), nullable=True),
        sa.Column("gtin", sa.String(), nullable=True),
        sa.Column("pack_size", sa.String(), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_packages_gtin"), "packages", ["gtin"], unique=True)
    op.create_table(
        "pharmacy_inventory",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("pharmacy_id", sa.String(), nullable=False),
        sa.Column("package_id", sa.String(), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("availability", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pharmacy_id"],
            ["pharmacies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_images",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("package_id", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column("pharmacies", "address", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("pharmacies", "lat", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("pharmacies", "lng", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("pharmacies", "phone", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "pharmacies",
        "opening_hours",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.add_column("products", sa.Column("inn_name", sa.String(), nullable=False))
    op.add_column("products", sa.Column("atc_code", sa.String(), nullable=True))
    op.alter_column("products", "form", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("products", "strength", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(op.f("ix_products_gtin"), table_name="products")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.create_index(
        op.f("ix_products_atc_code"), "products", ["atc_code"], unique=False
    )
    op.create_index(
        op.f("ix_products_inn_name"), "products", ["inn_name"], unique=False
    )
    op.drop_column("products", "currency")
    op.drop_column("products", "name")
    op.drop_column("products", "price_cents")
    op.drop_column("products", "pharmacy_id")
    op.drop_column("products", "gtin")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("gtin", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "products",
        sa.Column("pharmacy_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "products",
        sa.Column("price_cents", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "products", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "products",
        sa.Column("currency", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_products_inn_name"), table_name="products")
    op.drop_index(op.f("ix_products_atc_code"), table_name="products")
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    op.create_index(op.f("ix_products_gtin"), "products", ["gtin"], unique=False)
    op.alter_column("products", "strength", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("products", "form", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("products", "atc_code")
    op.drop_column("products", "inn_name")
    op.alter_column(
        "pharmacies",
        "opening_hours",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column("pharmacies", "phone", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("pharmacies", "lng", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("pharmacies", "lat", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("pharmacies", "address", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_table("product_images")
    op.drop_table("pharmacy_inventory")
    op.drop_index(op.f("ix_packages_gtin"), table_name="packages")
    op.drop_table("packages")
    op.drop_table("translations")
    op.drop_index(op.f("ix_brands_brand_name"), table_name="brands")
    op.drop_table("brands")
    # ### end Alembic commands ###
