"""add translated_description, stock_quantity, last_updated, pharmacy location fields

Revision ID: 8c251db17dc2
Revises: 0dc2e3b71fd0
Create Date: 2025-09-03 20:02:29.529752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c251db17dc2'
down_revision: Union[str, Sequence[str], None] = '0dc2e3b71fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacies', sa.Column('country', sa.String(length=2), nullable=False))
    op.add_column('pharmacies', sa.Column('city', sa.String(), nullable=False))
    op.add_column('pharmacy_inventory', sa.Column('stock_quantity', sa.Integer(), nullable=True))
    op.add_column('pharmacy_inventory', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.drop_column('pharmacy_inventory', 'availability')
    op.add_column('translations', sa.Column('translated_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translations', 'translated_description')
    op.add_column('pharmacy_inventory', sa.Column('availability', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('pharmacy_inventory', 'last_updated')
    op.drop_column('pharmacy_inventory', 'stock_quantity')
    op.drop_column('pharmacies', 'city')
    op.drop_column('pharmacies', 'country')
    # ### end Alembic commands ###
