"""Seed some test data actually

Revision ID: d50e6c863412
Revises: 01a4d753aa07
Create Date: 2025-08-17 16:40:26.246818

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.seeds.seed_data import seed_database

# revision identifiers, used by Alembic.
revision: str = "d50e6c863412"
down_revision: Union[str, Sequence[str], None] = "01a4d753aa07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands NOT auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    seed_database(conn)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands NOT auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(text("DELETE FROM products;"))
    conn.execute(text("DELETE FROM pharmaces;"))
    # ### end Alembic commands ###
